name: Update Code Coverage Badge

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  update-coverage-badge:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      # Run tests and generate coverage report
      - name: Run tests and generate coverage report
        run: ./gradlew koverlog

      # Update coverage badge
      - name: Update Coverage Badge
        run: ./gradlew updateCoverageBadge

      # Define a timestamp variable
      - name: Set timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      # Extract branch name using your provided solution
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
        id: extract_branch

      # Create a Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.MY_GITHUB_SECRET }}
          title: "Update code coverage badge"
          body: "Automated update of the code coverage badge."
          base: main # specify the main branch as the base
          branch: update-coverage-badge-${{ env.TIMESTAMP }}